package: store
version: 1.2.2
name: Store
author: Joachim Doerr
supportpage: https://joachim-doerr.com

page:
    title: 'translate:store_title'
    perm: store[]
#    block: store_configuration
    icon: rex-icon fa-shopping-cart
    subpages:
        settings: { title: 'translate:store_settings', perm: storeadmin[] }
        list_form: { title: '', perm: storeadmin[], hidden: 1 }

system_plugins:
    - channels
    - products
    - tools
    - zones