package: store
version: 1.2.2
name: Store
author: Joachim Doerr
supportpage: https://joachim-doerr.com

page:
    title: ''
    perm: store[]
    hidden: true
    subpages:
        list_form:
            title: ''
            perm: store[]
            hidden: true

#system_plugins:
#    - channels
#    - products
#    - tools
#    - zones